# Generated by Django 6.0.4 on 2026-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
