# Generated by Django 6.0.4 on 2026-05-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите тему письма",
                        max_length=50,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текст письма", verbose_name="текст письма"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите email", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите фамилию",
                        max_length=50,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Введите имя", max_length=50, verbose_name="Имя"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите отчество",
                        max_length=50,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Введите комментарий",
                        null=True,
                        verbose_name="комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
                "ordering": ("email",),
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Введите дату и время начала рассылки",
                        verbose_name="Начало рассылки",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Введите дату и время конца рассылки",
                        verbose_name="Конец рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Создана"),
                            ("RUN", "Запущена"),
                            ("FINISHED", "Завершена"),
                        ],
                        max_length=20,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="mailing.message",
                        verbose_name="сообщение",
                    ),
                ),
                ("recipients", models.ManyToManyField(to="mailing.recipient")),
            ],
        ),
    ]
