# Generated by Django 6.0.4 on 2026-05-14 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_attemptmailing_alter_mailing_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="владелец",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messeges",
                to=settings.AUTH_USER_MODEL,
                verbose_name="сообщения",
            ),
        ),
        migrations.AddField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="владелец",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="name",
            field=models.CharField(
                help_text="Введите название рассылки",
                max_length=200,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создана"),
                    ("RUN", "Запущена"),
                    ("FINISHED", "Завершена"),
                    ("turned-off", "Отключена"),
                ],
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recipient",
            unique_together={("email", "owner")},
        ),
        migrations.AddField(
            model_name="attemptmailing",
            name="mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="mailing.mailing",
                verbose_name="рассылка",
            ),
        ),
    ]
